name: WillyWeather Radar
version: "1.0.4"
slug: willyweather_radar
description: Fetch and serve WillyWeather radar imagery with blending support
url: https://github.com/safepay/willyweather-radar-addon
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
startup: application
boot: auto
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: Web interface
ingress: true
ingress_port: 8099
panel_icon: mdi:weather-pouring
options:
  api_key: ""
  cache_duration: 300
  log_level: info
schema:
  api_key: str
  cache_duration: int(60,3600)?
  log_level: list(debug|info|warning|error)?
